// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SurfTrackerBackend.Data;

#nullable disable

namespace SurfTrackerBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616232611_AddDatabaseTables")]
    partial class AddDatabaseTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SurfTrackerBackend.Models.Domain.SurfSession", b =>
                {
                    b.Property<int>("SurfSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurfSessionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SurfSpotId")
                        .HasColumnType("int");

                    b.Property<int>("SurfboardId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SurfSessionId");

                    b.HasIndex("SurfSpotId");

                    b.HasIndex("SurfboardId");

                    b.HasIndex("UserId");

                    b.ToTable("SurfSessions");
                });

            modelBuilder.Entity("SurfTrackerBackend.Models.Domain.SurfSessionSwell", b =>
                {
                    b.Property<int>("SurfSessionSwellId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurfSessionSwellId"));

                    b.Property<int?>("OceanCurrentDirection")
                        .HasColumnType("int");

                    b.Property<decimal?>("OceanCurrentVelocity")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("SeaLevelHeightMsl")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("SeaSurfaceTemperature")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("SecondarySwellWaveDirection")
                        .HasColumnType("int");

                    b.Property<decimal?>("SecondarySwellWaveHeight")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("SecondarySwellWavePeriod")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("SurfSessionId")
                        .HasColumnType("int");

                    b.Property<int?>("SwellWaveDirection")
                        .HasColumnType("int");

                    b.Property<decimal?>("SwellWaveHeight")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("SwellWavePeriod")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WaveDirection")
                        .HasColumnType("int");

                    b.Property<decimal?>("WaveHeight")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("WavePeriod")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("WindWaveDirection")
                        .HasColumnType("int");

                    b.Property<decimal?>("WindWaveHeight")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("WindWavePeriod")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("SurfSessionSwellId");

                    b.HasIndex("SurfSessionId", "Time")
                        .IsUnique();

                    b.ToTable("SurfSessionSwell", (string)null);
                });

            modelBuilder.Entity("SurfTrackerBackend.Models.Domain.SurfSessionUserObservation", b =>
                {
                    b.Property<int>("SurfSessionUserObservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurfSessionUserObservationId"));

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("SurfSessionId")
                        .HasColumnType("int");

                    b.HasKey("SurfSessionUserObservationId");

                    b.HasIndex("SurfSessionId");

                    b.ToTable("SurfSessionUserObservations");
                });

            modelBuilder.Entity("SurfTrackerBackend.Models.Domain.SurfSessionWeather", b =>
                {
                    b.Property<int>("SurfSessionWeatherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurfSessionWeatherId"));

                    b.Property<int?>("CloudCover")
                        .HasColumnType("int");

                    b.Property<decimal?>("Precipitation")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("SurfSessionId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Temperature2m")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("UvIndex")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("WeatherCode")
                        .HasColumnType("int");

                    b.Property<int?>("WindDirection10m")
                        .HasColumnType("int");

                    b.Property<decimal?>("WindSpeed10m")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("SurfSessionWeatherId");

                    b.HasIndex("SurfSessionId", "Time")
                        .IsUnique();

                    b.ToTable("SurfSessionWeather");
                });

            modelBuilder.Entity("SurfTrackerBackend.Models.Domain.SurfSpot", b =>
                {
                    b.Property<int>("SurfSpotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurfSpotId"));

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SurfSpotId");

                    b.HasIndex("UserId");

                    b.ToTable("SurfSpots");
                });

            modelBuilder.Entity("SurfTrackerBackend.Models.Domain.Surfboard", b =>
                {
                    b.Property<int>("SurfboardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurfboardId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SurfboardId");

                    b.HasIndex("UserId");

                    b.ToTable("Surfboards");
                });

            modelBuilder.Entity("SurfTrackerBackend.Models.Domain.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("CognitoId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("CognitoId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SurfTrackerBackend.Models.Domain.SurfSession", b =>
                {
                    b.HasOne("SurfTrackerBackend.Models.Domain.SurfSpot", "SurfSpot")
                        .WithMany("SurfSessions")
                        .HasForeignKey("SurfSpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SurfTrackerBackend.Models.Domain.Surfboard", "Surfboard")
                        .WithMany("SurfSessions")
                        .HasForeignKey("SurfboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SurfTrackerBackend.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurfSpot");

                    b.Navigation("Surfboard");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SurfTrackerBackend.Models.Domain.SurfSessionSwell", b =>
                {
                    b.HasOne("SurfTrackerBackend.Models.Domain.SurfSession", "SurfSession")
                        .WithMany("Swells")
                        .HasForeignKey("SurfSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurfSession");
                });

            modelBuilder.Entity("SurfTrackerBackend.Models.Domain.SurfSessionUserObservation", b =>
                {
                    b.HasOne("SurfTrackerBackend.Models.Domain.SurfSession", "SurfSession")
                        .WithMany("UserObservations")
                        .HasForeignKey("SurfSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurfSession");
                });

            modelBuilder.Entity("SurfTrackerBackend.Models.Domain.SurfSessionWeather", b =>
                {
                    b.HasOne("SurfTrackerBackend.Models.Domain.SurfSession", "SurfSession")
                        .WithMany("WeatherRecords")
                        .HasForeignKey("SurfSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurfSession");
                });

            modelBuilder.Entity("SurfTrackerBackend.Models.Domain.SurfSpot", b =>
                {
                    b.HasOne("SurfTrackerBackend.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SurfTrackerBackend.Models.Domain.Surfboard", b =>
                {
                    b.HasOne("SurfTrackerBackend.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SurfTrackerBackend.Models.Domain.SurfSession", b =>
                {
                    b.Navigation("Swells");

                    b.Navigation("UserObservations");

                    b.Navigation("WeatherRecords");
                });

            modelBuilder.Entity("SurfTrackerBackend.Models.Domain.SurfSpot", b =>
                {
                    b.Navigation("SurfSessions");
                });

            modelBuilder.Entity("SurfTrackerBackend.Models.Domain.Surfboard", b =>
                {
                    b.Navigation("SurfSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
